# Generated by Django 3.2.23 on 2024-02-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaf',
            name='recommendations',
            field=models.ManyToManyField(blank=True, null=True, related_name='leaves', to='main.Recommendation'),
        ),
    ]
