# Generated by Django 3.2.23 on 2024-02-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_leaf_recommendations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='crop',
            name='leaves',
            field=models.ManyToManyField(blank=True, related_name='crops', to='main.Leaf'),
        ),
        migrations.AlterField(
            model_name='leaf',
            name='recommendations',
            field=models.ManyToManyField(related_name='leaves', to='main.Recommendation'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='crops',
            field=models.ManyToManyField(blank=True, related_name='users', to='main.Crop'),
        ),
    ]
