# Generated by Django 3.2.23 on 2024-02-03 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_leaf_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaf',
            name='crop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.crop'),
            preserve_default=False,
        ),
    ]
