# Generated by Django 3.2.23 on 2024-02-04 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaf',
            name='crop',
        ),
    ]
