# Generated by Django 3.2.23 on 2024-02-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_leaf_recommendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='content',
            field=models.CharField(max_length=1500),
        ),
    ]
