# Generated by Django 3.2.23 on 2024-02-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_recommendation_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='crop_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
