name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy to VPS"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run:  |
          mkdir -p /home/runner/.ssh/
          echo "$SSH_PRIVATE_KEY" > /home/runner/.ssh/deploy-key.pem
          chmod 600 /home/runner/.ssh/deploy-key.pem
          cat >> /home/runner/.ssh/config <<END
          Host my-vps
            HostName $SSH_IP
            User $SSH_USER
            IdentityFile /home/runner/.ssh/deploy-key.pem
            StrictHostKeyChecking no
            port $SSH_PORT
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_IP: ${{ secrets.SSH_IP }}
          SSH_PORT: ${{ secrets.SSH_PORT }}

      - name: Deploy site
        run: ssh my-vps 
          'cd ${{ secrets.PROJECT_ROOT }} && cd .. && git pull && pip3 install -r requirements.txt && cd qhacks && python manage.py migrate && sudo systemctl stop qhacks && sudo systemctl start qhacks'